### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by OlegMalkov** [OlegMalkov/epicsFlow#1]
- [ ] selector function on condition
- [ ] resetAllConditionsBelowThis feature
- [ ] deep freeze object before passing to epic updater reducer/effect manager in dev env
- [ ] undo
- [ ] error reporting (rich api to generate crash reports with data to reproduce exception)
- [ ] a way to recover app on render exception
- [ ] network effect manager
